name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish win-x64
      run: dotnet publish -p:PublishSingleFile=true -r win-x64 -c Release --self-contained false --no-restore
    - name: Publish linux-x64
      run: dotnet publish -p:PublishSingleFile=true -r linux-x64 -c Release --self-contained false --no-restore
    - name: Publish osx-x64
      run: dotnet publish -p:PublishSingleFile=true -r osx-x64 -c Release --self-contained false --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
